name: Build and Push to GHCR

on:
  push:
    branches:
      - main
    paths:
      - Containerfile
      - konveyor-v0.0.13.vsix

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout Code
        uses: actions/checkout@v3

      - name: 🔧 Set up Podman
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏗️ Build Image with Podman
        run: |
          podman build -f Containerfile -t ghcr.io/${{ github.repository_owner }}/kai-devspaces:latest .

      - name: 📤 Push Image to GHCR
        run: |
          podman push ghcr.io/${{ github.repository_owner }}/kai-devspaces:latest

