name: Build and Push to GHCR and Quay

on:
  push:
    branches:
      - main
    paths:
      - 'Containerfile'
      - '.github/workflows/build-and-publish-ghcr.yml'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push container images
        run: |
          GHCR_IMAGE=ghcr.io/${{ github.repository_owner }}/kai-devspaces:latest
          QUAY_IMAGE=quay.io/ibolton/kai-devspaces:latest
          
          # Build image
          podman build -f Containerfile -t $GHCR_IMAGE -t $QUAY_IMAGE .
          
          # Push to both registries
          podman push $GHCR_IMAGE
          podman push $QUAY_IMAGE

